// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApjf_sX-abhQslfqJryvpTAoEhcjZg4g',
    appId: '1:121072315639:web:10441500fb3293bcbd77f2',
    messagingSenderId: '121072315639',
    projectId: 'skilltap-6315c',
    authDomain: 'skilltap-6315c.firebaseapp.com',
    storageBucket: 'skilltap-6315c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-4PKo8gtruFDpqtvgfpwbKTJnXhRiO4',
    appId: '1:121072315639:android:df768d3d8425af40bd77f2',
    messagingSenderId: '121072315639',
    projectId: 'skilltap-6315c',
    storageBucket: 'skilltap-6315c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3d-G6G07mEE81cw6Rqw4fat9NCN3t2FU',
    appId: '1:121072315639:ios:5811f7e9ef5509e6bd77f2',
    messagingSenderId: '121072315639',
    projectId: 'skilltap-6315c',
    storageBucket: 'skilltap-6315c.firebasestorage.app',
    iosBundleId: 'com.example.skillset',
  );
}
